# Generated by Django 6.0.3 on 2026-04-20 22:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Название')),
                ('params_json', models.JSONField(blank=True, default=dict, verbose_name='Параметры поиска')),
                ('params_hash', models.CharField(editable=False, max_length=64, verbose_name='Хэш параметров')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Сохранённый поиск')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано')),
                ('executed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний запуск')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'db_table': 'search_entries',
                'ordering': ('user_id', '-executed_at', '-id'),
                'indexes': [models.Index(fields=['user', '-executed_at'], name='idx_search_entry_user_updated'), models.Index(fields=['user', 'is_saved'], name='idx_search_entry_user_saved')],
                'constraints': [models.UniqueConstraint(fields=('user', 'params_hash'), name='uniq_search_entry_user_params_hash')],
            },
        ),
    ]
